{{- if not .Values.geth.generatedPasswordSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "geth-node.fullname" . }}-generated-password
  labels:
    app: {{ template "geth-node.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  password: {{ randAlphaNum 30 | b64enc | quote }}
{{- end }}