{{- if not (.Values.geth.accountAddress) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "geth-node.fullname" . }}-keystore-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Mi
{{- end }}