apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "geth-node.fullname" . }}
  labels:
    app: {{ template "geth-node.name" . }}
    chart: {{ template "geth-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "geth-node.fullname" . }}
  replicas: {{ .Values.geth.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "geth-node.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "geth-node.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: geth
          image: {{ .Values.geth.image.repository }}:{{ .Values.geth.image.tag }}
          resources:
            requests:
              memory: {{ .Values.geth.memory }}
            limits:
              memory: {{ .Values.geth.memory }}
          imagePullPolicy: {{ .Values.geth.imagePullPolicy }}
          command: [ "/bin/sh", "startup.sh" ]
          ports:
            - name: rpc
              containerPort: 8545
          volumeMounts:
            - name: data
              mountPath: {{ .Values.geth.datadir }}
            - name: geth-startup
              mountPath: /startup.sh
              subPath: startup.sh
{{- if .Values.geth.networkid }}
            - name: genesis-cfg
              mountPath: /genesis.json
              subPath: genesis.json
{{- end}}
      volumes:
        - name: geth-startup
          configMap:
            defaultMode: 0700
            name: geth-startup
{{- if .Values.geth.networkid }}
        - name: genesis-cfg
          configMap:
            name: geth-config
{{- end}}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: {{ template "geth-node.name" . }}
          release: "{{ .Release.Name }}"
      spec:
        storageClassName: {{ .Values.geth.storageClass }}
        accessModes:
          - {{ .Values.geth.accessMode }}
        resources:
          requests:
            storage: {{ .Values.geth.storage }}