apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "geth-node.fullname" . }}
  labels:
    app: {{ template "geth-node.name" . }}
    chart: {{ template "geth-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "geth-node.fullname" . }}
  replicas: {{ .Values.geth.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "geth-node.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "geth-node.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: geth
          image: {{ .Values.geth.image.repository }}:{{ .Values.geth.image.tag }}
          resources:
            requests:
              memory: {{ .Values.geth.memory }}
            limits:
              memory: {{ .Values.geth.memory }}
          imagePullPolicy: {{ .Values.geth.imagePullPolicy }}
          command: [ "/bin/sh", "startup.sh" ]
          ports:
            - name: rpc
              containerPort: 8545
          volumeMounts:
            - name: data
              mountPath: {{ .Values.geth.dataDir }}/geth
            - name: {{ template "geth-node.fullname" . }}-startup
              mountPath: /startup.sh
              subPath: startup.sh
{{- if .Values.geth.accountAddress }}
            - name: key
              mountPath: "{{.Values.geth.dataDir}}/keystore/"
              readOnly: true
{{- else}}
            - name: {{ template "geth-node.fullname" . }}-account-pvc
              mountPath: {{ .Values.geth.dataDir }}/accounts
            - name: password
              mountPath: "/password"
              readOnly: true
{{- end}}
{{- if .Values.geth.networkId }}
            - name: genesis-cfg
              mountPath: /genesis.json
              subPath: genesis.json
{{- end}}
      volumes:
        - name: {{ template "geth-node.fullname" . }}-startup
          configMap:
            defaultMode: 0700
            name: {{ template "geth-node.fullname" . }}-startup
{{- if .Values.geth.accountAddress }}
        - name: key
          secret:
            secretName: {{ .Values.geth.accountSecrets }}
            items:
              - key: keyfile
                path: UTC--1998-09-19T09-00-00.000000000Z--{{ .Values.geth.accountAddress }}
{{- else}}
        - name: key
          persistentVolumeClaim:
            claimName: {{ template "geth-node.fullname" . }}-keystore-pvc
        - name: {{ template "geth-node.fullname" . }}-account-pvc
          persistentVolumeClaim:
            claimName: {{ template "geth-node.fullname" . }}-account-pvc
        - name: password
          secret:
{{- if .Values.geth.generatedPasswordSecretName }}
            secretName: {{ .Values.geth.generatedPasswordSecretName }}
{{- else}}
            secretName: {{ template "geth-node.fullname" . }}-generated-password
{{- end}}
            items:
              - key: password
                path: accountPassword
{{- end}}
{{- if .Values.geth.networkId }}
        - name: genesis-cfg
          configMap:
            name: {{ template "geth-node.fullname" . }}-config
{{- end}}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: {{ template "geth-node.name" . }}
          release: "{{ .Release.Name }}"
      spec:
        storageClassName: {{ .Values.geth.storageClass }}
        accessModes:
          - {{ .Values.geth.accessMode }}
        resources:
          requests:
            storage: {{ .Values.geth.storage }}