apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "geth-helm.fullname" . }}
  labels:
    app: {{ template "geth-helm.name" . }}
    chart: {{ template "geth-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "geth-helm.fullname" . }}
  replicas: {{ .Values.geth.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "geth-helm.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "geth-helm.name" . }}
        release: {{ .Release.Name }}
    spec:
      hostIPC: true
      initContainers:
#        - name: volumne-permissions
#          image: {{ .Values.geth.image.repository }}:{{ .Values.geth.image.tag }}
#          command: ["/bin/sh"]
#          args: ["-c", "chmod -R 755 /root/.ethereum"]
#          volumeMounts:
#            - name: data
#              mountPath: /root/.ethereum
        - name: geth-init
          image: {{ .Values.geth.image.repository }}:{{ .Values.geth.image.tag }}
          command: ["geth"]
          args: ["init", "/root/.ethereum/.genesis"]
          volumeMounts:
            - name: data
              mountPath: /root/.ethereum
            - name: config
              mountPath: /root/.ethereum/.genesis
              subPath: genesis.json
      containers:
      - name: geth
        image: {{ .Values.geth.image.repository }}:{{ .Values.geth.image.tag }}
        resources:
          requests:
            memory: "8000Mi"
          limits:
            memory: "8500Mi"
        imagePullPolicy: {{ .Values.geth.imagePullPolicy }}
        command: ["geth"]
        args:
        - --http
        - --http.corsdomain=*
        - --http.vhosts=*
        - --http.addr=0.0.0.0
        - --cache=1024
        - --ipcdisable
        - --datadir=/root/.ethereum/
        ports:
        - name: rpc
          containerPort: 8545
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
      volumes:
        - name: config
          configMap:
              name: {{ template "geth-helm.name" . }}-config

  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: {{ template "geth-helm.name" . }}
        release: "{{ .Release.Name }}"
    spec:
      storageClassName: {{ .Values.geth.storageClass }}
      accessModes:
        - {{ .Values.geth.accessMode | quote }}
      resources:
          requests:
            storage: {{ .Values.geth.storage | quote }}
