kind: Service
apiVersion: v1
metadata:
  name: {{ template "geth-node.name" . }}-service
  labels:
    app: {{ template "geth-node.name" . }}
    chart: {{ template "geth-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "geth-node.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - port: {{ .Values.service.rpcPort }}
      targetPort: {{ .Values.service.rpcPort }}
      protocol: TCP
      name: http